use_frameworks!

target 'Fadeable_Example' do
  pod 'Fadeable', :path => '../'

  target 'Fadeable_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
